name: Build and Push

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      project_id:
        description: "GCP project ID"
        required: true
        type: string
      service_account:
        description: "GCP service account for authentication"
        required: true
        type: string
      workload_identity_provider:
        description: "Full provider resource name (e.g. projects/302…/providers/github)"
        required: true
        type: string
      region:
        description: "GCP region"
        required: true
        type: string
      tag:
        description: "Tag for the Docker image, if not provided, the SHA will be used"
        required: false
        type: string
      repository:
        description: "Artifact Registry repository name"
        required: false
        type: string
        default: "cloud-run-source-deploy"
    outputs:
      image-url:
        description: "The full URL of the built Docker image"
        value: ${{ jobs.build-and-push.outputs.image-url }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image-url: ${{ steps.set-outputs.outputs.image-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.project_id }}

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev

      - name: Set output
        id: set-outputs
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            IMAGE_URL="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.repository || 'cloud-run-source-deploy' }}/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ inputs.tag }}"
          else
            IMAGE_URL="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.repository || 'cloud-run-source-deploy' }}/${{ github.repository_owner }}/${{ github.event.repository.name }}/sha:${{ github.sha }}"
          fi
          echo "image-url=$IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.set-outputs.outputs.image-url }} .

      - name: Push Docker image
        run: docker push ${{ steps.set-outputs.outputs.image-url }}
